### ISSUE TITLE
Auto update the glossary

### ISSUE THREAD

**Issue by Mte90** [Mte90/GlotDict#37]
Add a button that download the last glossary.

## Roadmap

* [x] Online service that generate the last glossaries
* [x] Add in GlotDictJSON support for versioning the glossaries in case of new features
* [x] Generate the list of language based from the list download
* [x] Think a cache system for all the different versions of glossaries locally
